### ISSUE TITLE
Can't add NuGet package to Xamarin project in  Visual Studio for Mac Preview

### ISSUE THREAD

**Issue by wilvoss** [xoofx/zio#2]
Attempting to gather dependency information for package 'Zio.0.1.0' with respect to project 'Xamarin.HealthVault.UX.Prototoyping', targeting '.NETPortable,Version=v4.5,Profile=Profile111'
  GET https://api.nuget.org/v3/registration1-gz/zio/index.json
  OK https://api.nuget.org/v3/registration1-gz/zio/index.json 438ms
Total number of results gathered : 1
Gathering dependency information took 518.52 ms
Summary of time taken to gather dependencies per source :
https://api.nuget.org/v3/index.json	-	475.58 ms
Attempting to resolve dependencies for package 'Zio.0.1.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Zio.0.1.0'
Resolved actions to install package 'Zio.0.1.0'
Retrieving package 'Zio 0.1.0' from 'nuget.org'.
For adding package 'Zio.0.1.0' to project 'Xamarin.HealthVault.UX.Prototoyping' that targets 'portable45-net45+win8+wpa81'.
Install failed. Rolling back...
Package 'Zio.0.1.0' does not exist in project 'Xamarin.HealthVault.UX.Prototoyping'
Package 'Zio.0.1.0' does not exist in folder '/Users/wilvoss/Projects/DefaultCollection/Health/_git/health-design/Prototypes/UX/SleepyTime/SleepyTime/packages'
Executing nuget actions took 200.59 ms
Could not install package 'Zio 0.1.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by xoofx** [comment]
afaik, Zio can't target `.NETPortable,Version=v4.5,Profile=Profile111` because PCL profiles don't provide the `System.IO.File` and `System.IO.Directory` and `System.IO.DriveInfo` used by Zio.

Zio supports [.NET Standard 1.3](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.3.md) which can target mobile platforms. Couldn't you migrate your project to .NETStandard 1.3?
