### ISSUE TITLE
Is there any way to save the MemoryFileSystem instance to a file or byte array.

### ISSUE THREAD

**Issue by chang196700** [xoofx/zio#45]
I tried BinaryFormatter, but failed. It said `Type 'Zio.FileSystems.MemoryFileSystem' in Assembly 'Zio, Version=0.7.4.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.`

**Comment by xoofx** [comment]
No, `MemoryFileSystem` is not serializable.
