### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Ellested** [xoofx/zio#47]
/a                       | fs2
    file1.txt            | fs2
    file2.txt            | fs1
    **file4.txt            | fs1**
/b                       | fs2
    file5.txt            | fs2
file3.txt                | fs1

Just a typo in the documentation I think - I would expect file4,txt to exist on fs2?

**Comment by Ellested** [comment]
Sure I can fix it, but was I right?
I guess since you've added PR welcome, but please confirm.

**Comment by xoofx** [comment]
Yeah, sorry, I edited directly the file. I tagged this as a PR, but that was easier to fix the typo directly. Thanks!
