### ISSUE TITLE
Drive letter casing

### ISSUE THREAD

**Issue by Ellested** [xoofx/zio#48]
Hi,

First of all, this library is really nice, and well written - very good job :-)

There's a small glitch in that you can actually mount windows file systems with uppercase drive letters and it seems to work fine, until you try and enumerate the directories.

Maybe, it can be more forgiving by aligning the drive letter casing somewhere?

![image](https://user-images.githubusercontent.com/7518147/79024752-34cd7100-7b84-11ea-9747-dfe9d9eed9f3.png)

**Comment by xoofx** [comment]
Indeed, PR welcome for a fix.

**Comment by xoofx** [comment]
Actually I should provide a fix as I have another commit to add and a new version to release.

**Comment by xoofx** [comment]
> There's a small glitch in that you can actually mount windows file systems with uppercase drive 
 letters and it seems to work fine, until you try and enumerate the directories.
> 
> Maybe, it can be more forgiving by aligning the drive letter casing somewhere?

So I will throw an exception probably at creation time instead to match the behavior on Linux (it would be confusing that the same program works on windows but not on WSL for instance)

**Comment by xoofx** [comment]
Should be fixed in 0.8.0
