### ISSUE TITLE
Moving SearchOption from the System.IO to library

### ISSUE THREAD

**Issue by sytone** [xoofx/zio#52]
If other file systems are used it seems a bit artificial to have to reference System.IO for the SearchOption enum. Is there a reason for this deign?

**Comment by xoofx** [comment]
> If other file systems are used it seems a bit artificial to have to reference System.IO for the SearchOption enum. Is there a reason for this deign?

Not sure to understand the question... Zio is relying on many `System.IO` types including `SearchOption` but also `FileMode`, `FileAccess`, `FileShare`, `FileAttributes`, `IOException`, `FileNotFoundException`...etc. Replicating these types in Zio would not make much sense, it's an abstract file system, but it's not built on a vaccum, it still follows the existing ecosystem. Does that respond to your question?

**Comment by sytone** [comment]
Yes, thanks!
