### ISSUE TITLE
MemoryFileSystem.CreateDirectory fails at create "/"

### ISSUE THREAD

**Issue by sebastienros** [xoofx/zio#61]
Like the standard `System.IO` API to create a directory, it processes all segments in the path. However when using something like `fs.CreateDirectory("/a/b/c");` in Zio it will fail with `System.UnauthorizedAccessException : Cannot create root directory '/'`.

I would have expected it to ignore `/` since it already exists.

**Comment by sebastienros** [comment]
Apparently I made a mistake and it happens when calling `CreateDirectory("/")` specifically.

I am doing `fs.CreateDirectory(path.GetDirectory());` and in this case the path was `/index.html`. I would still expect it not to throw.

**Comment by xoofx** [comment]
What type of `fs` is?

**Comment by sebastienros** [comment]
Happened with `MemoryFileSystem`.

**Comment by xoofx** [comment]
Yeah, it's a bug

**Comment by xoofx** [comment]
Fixed by commit f1e9350
